### ISSUE TITLE
More info on npm i -g @forgerock/fr-config-manager install option

### ISSUE THREAD

**Issue by nigelelliott75** [ForgeRock/fr-config-manager#162]
In the README.md ir indicates that `npm i -g @forgerock/fr-config-manager` can be used to do the install, however when I try this get the following error:

> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@forgerock%2ffr-config-manager - Not found

So @forgerock/fr-config-manager is not available via the main npm registry, if it is available via a different registry or if it is up to us to add @forgerock/fr-config-manager to our local registry then it would be good to add this clarity to the README.md file.

**Comment by christian-brindley** [comment]
The README update is a little premature - we are still in the process of getting the package published on npmjs. I will update accordingly, and re-instate this instruction once the package is public.
