### ISSUE TITLE
Scripts for DeviceMatchNode

### ISSUE THREAD

**Issue by cuttin-n-pastin** [ForgeRock/fr-config-manager#184]
Hello,

fr-config-pull does not pull decision node scripts for nodes other than `ScriptedDecisionNode` and `ConfigProviderNode`. In particular, it will ignore scripts for `DeviceMatchNode`. The nuance with these scripts: they should only be pulled/pushed if `useScript: true`.

Any plans to support or general thoughts? Thank you!

**Comment by christian-brindley** [comment]
These types of nodes with conditional scripts have not been considered up to now: this is an issue which should be addressed.

**Comment by christian-brindley** [comment]
Updating dependency logic to pull/push scripts for any node which has a `script` property. If there is a `useScript` property, this overrides the script pull/push if set to `false`.

**Comment by cuttin-n-pastin** [comment]
Thank you!
