### ISSUE TITLE
idm authentication config

### ISSUE THREAD

**Issue by TasosKampas** [ForgeRock/fr-config-manager#195]
Add the ability to pull / push the IDM authentication.json

**Comment by christian-brindley** [comment]
It's pretty unusual to touch the IDM authentication config in cloud, but we could add it as a command. In the meantime you could use the raw command to fetch it by path?

**Comment by TasosKampas** [comment]
Yep, the raw command can fetch it nicely. There can be cases like custom org admin type or OAuth2 apps accessing custom endpoints via an internal role, instead of a service account. In both cases, the authentication.json needs to be updated - although generally, we'd prefer not to touch it.

**Comment by TasosKampas** [comment]
Somehow I missed that you can do _fr-config-push raw_  - so that's should be sufficient.
