### ISSUE TITLE
Theme export error: themes.forEach is not a function

### ISSUE THREAD

**Issue by anurag-gangrade** [ForgeRock/fr-config-manager#196]
Hi,
While we were trying to export our identity cloud tenant static repo using jenkins we are getting the following error-
`20:24:29  + /home/jenkins/.nvm/versions/node/v16.18.1/bin/fr-config-pull all-static
20:24:29  Getting email templates
20:24:29  Getting email provider settings
20:24:29  Getting managed objects
20:24:29  Getting scripts
20:24:29  Getting journeys
20:24:29  Getting endpoints
20:24:29  Getting schedules
20:24:29  Getting connectors
20:24:29  Getting mappings
20:24:29  Getting access config
20:24:29  Getting cors config
20:24:29  Getting password policy
20:24:29  Getting themes
20:24:29  Getting terms and conditions
20:24:29  Getting KBA
20:24:29  Getting services
20:24:29  Getting authentication config
20:24:29  Getting RCS config
20:24:29  Getting UI config
20:24:29  Getting locales
20:24:29  Getting audit settings
20:24:29  Getting org privileges config
20:24:30  TypeError: themes.forEach is not a function
20:24:30      at processThemes (/tmp/tvh-fr-frconfigmgr/fr-config-manager/packages/fr-config-pull/src/scripts/themes.js:18:12)
20:24:30      at Object.exportThemes (/tmp/tvh-fr-frconfigmgr/fr-config-manager/packages/fr-config-pull/src/scripts/themes.js:103:7)
20:24:30      at processTicksAndRejections (node:internal/process/task_queues:96:5)`

We are using the latest version of fr-config-manager.
Could you please help us to resolve this issue or suggest a workaround for it?

**Comment by christian-brindley** [comment]
This is fixed by https://github.com/ForgeRock/fr-config-manager/issues/178 - we need to issue a new release to include this - working on this now.

**Comment by christian-brindley** [comment]
Fixed in 1.4.6

**Comment by christian-brindley** [comment]
This fix was to handle a missing realm in the themes config. I have updated to handle themes with an entry for the realm, where the entry has a value of null. This is in the main branch - version 1.4.7-beta.1.

**Comment by anurag-gangrade** [comment]
Hi @christian-brindley ,

As per our analysis, the issue was caused by the Bravo realm's  theme. Upon reviewing the theme's JSON file, we found that it was structured as an object. Since the forEach function in the 'theme.js' script in fr-config-manager is designed to iterate over an array, this mismatch was causing the error.

To address the issue, we implemented a workaround by creating a test journey within the Bravo realm and setting the theme as the default for this specific journey. Afterward, we deleted the journey. By following this process, the theme's JSON was automatically converted into an array format.

Please note that we did not make any changes to the theme itself; we simply applied it as the default for a test journey.

Bravo realm theme original Json-
```
        "bravo": {
            "backgroundColor": "#324054",
            "backgroundImage": "",
            "buttonRounded": "4",
            "linkActiveColor": "#0A6EAB",
            "linkColor": "#109CF1",
            "logo": "data:image/svg+xml;base64,PHN2ZyB3******",
	    "logoProfile": "data:image/svg+xml;base64,PHN2ZyB3******",
            "primaryColor": "#324054",
            "primaryOffColor": "#242E3C",
            "profileBackgroundColor": "#FFFFFF",
            "profileMenuHighlightColor": "#f3f5f8",
            "profileMenuTextHighlightColor": "#FFFFFF",
            "textColor": "#FFFFFF"
        }
```
		
Bravo realm theme After change Json-
```
	"bravo": [
            {
                "backgroundColor": "#324054",
                "backgroundImage": "",
                "buttonRounded": "4",
                "linkActiveColor": "#0A6EAB",
                "linkColor": "#109CF1",
                "logo": "data:image/svg+xml;base64,PHN2ZyB3******",
                "logoProfile": "data:image/svg+xml;base64,PHN2ZyB3******",
                "primaryColor": "#324054",
                "primaryOffColor": "#242E3C",
                "profileBackgroundColor": "#FFFFFF",
                "profileMenuHighlightColor": "#f3f5f8",
                "profileMenuTextHighlightColor": "#FFFFFF",
                "textColor": "#FFFFFF",
                "_id": "e4b931e3-*******",
                "isDefault": true,
                "name": "****",
                "linkedTrees": []
            }
        ]
```

Additionally, could you please look into whether a logic can be implemented in the theme.js script itself? Specifically, it would be helpful if the script could iterate over a theme structured as a JSON object itself.

Thanks.

**Comment by christian-brindley** [comment]
Thank you for the analysis @anurag-gangrade - very helpful. Will look at handling this scenario in the tool - and will also investigate why this is happening in the platform as well.
