### ISSUE TITLE
Allow help when PUSH_NAMED_ONLY is set

### ISSUE THREAD

**Issue by kevswiss** [ForgeRock/fr-config-manager#202]
When PUSH_NAMED_ONLY  is set to true, it is not possible to get list available commands or get help output

fr-config-push --help
Push only permitted by name

fr-config-push services --help                         
Push only permitted by name

**Comment by christian-brindley** [comment]
I have fixed this as part of the improvements to named only and permitted commands - will be 1.4.8-beta.2
