### ISSUE TITLE
Error when pushing a task scanner scheduler to the tenant

### ISSUE THREAD

**Issue by nigelelliott75** [ForgeRock/fr-config-manager#204]
There is a bug in /main/packages/fr-config-push/src/scripts/update-idm-schedules.js where the variable is wrong

If I try and push a task scanner scheduler I get the following error:

**data is not defined**

![image](https://github.com/user-attachments/assets/73fb4773-36a8-48cb-bfab-1ba3ce301736)

The highlighted "data" in blue should be scriptData

**Comment by christian-brindley** [comment]
Issue can be reproduced - working on a fix.

**Comment by nigelelliott75** [comment]
@christian-brindley  Thank you for the quick turn around on this, do you know when it will be released and available to update via npm?

**Comment by christian-brindley** [comment]
Done - 1.4.7 is the latest release - also in npmjs
