### ISSUE TITLE
Error when pushing AM service that doesn't yet exist

### ISSUE THREAD

**Issue by kevswiss** [ForgeRock/fr-config-manager#218]
`sException processing request to https://openam-computershare-use1-dev.id.forgerock.io/am/json/realms/root/realms/alpha/realm-config/services/amSessionPropertyWhitelist{ code: 404, reason: 'Not Found', message: 'Not Found' }{  message: 'Request failed with status code 404',  name: 'AxiosError',  description: undefined,  number: undefined,  fileName: undefined,  lineNumber: undefined,  columnNumber: undefined,  stack: 'AxiosError: Request failed with status code 404\n' +    '    at settle (/home/cicdadmin/.nvm/versions/node/v18.20.4/lib/node_modules/@forgerock/fr-config-manager/node_modules/axios/dist/node/axios.cjs:2019:12)\n' +    '    at IncomingMessage.handleStreamEnd (/home/cicdadmin/.nvm/versions/node/v18.20.4/lib/node_modules/@forgerock/fr-config-manager/node_modules/axios/dist/node/axios.cjs:3135:11)\n' +    '    at IncomingMessage.emit (node:events:529:35)\n' +    '    at endReadableNT (node:internal/streams/readable:1400:12)\n' +    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n' +    '    at Axios.request (/home/cicdadmin/.nvm/versions/node/v18.20.4/lib/node_modules/@forgerock/fr-config-manager/node_modules/axios/dist/node/axios.cjs:4287:41)\n' +    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +    '    at async httpRequest (/home/cicdadmin/.nvm/versions/node/v18.20.4/lib/node_modules/@forgerock/fr-config-manager/packages/fr-config-common/src/restClient.js:109:20)\n' +    '    at async /home/cicdadmin/.nvm/versions/node/v18.20.4/lib/node_modules/@forgerock/fr-config-manager/packages/fr-config-push/src/scripts/update-services.js:54:11\n' +    '    at async Promise.all (index 1)\n' +    '    at async updateServices (/home/cicdadmin/.nvm/versions/node/v18.20.4/lib/node_modules/@forgerock/fr-config-manager/packages/fr-config-push/src/scripts/update-services.js:43:7)\n' +    '    at async updateStatic (/home/cicdadmin/.nvm/versions/node/v18.20.4/lib/node_modules/@forgerock/fr-config-manager/packages/fr-config-push/src/index.js:48:3)',  config: {    transitional: {      silentJSONParsing: true,      forcedJSONParsing: true,      clarifyTimeoutError: false    },    adapter: [ 'xhr', 'http', 'fetch' ],    transformRequest: [ [Function: transformRequest] ],    transformResponse: [ [Function: transformResponse] ],    timeout: 0,    xsrfCookieName: 'XSRF-TOKEN',    xsrfHeaderName: 'X-XSRF-TOKEN',    maxContentLength: -1,    maxBodyLength: -1,    env: { FormData: [Function], Blob: [class Blob] },    validateStatus: [Function: validateStatus],    headers: Object [AxiosHeaders] {      Accept: 'application/json, text/plain, */*',      'Content-Type': 'application/json',      Authorization: 'Bearer ***      'Accept-API-Version': 'protocol=1.0,resource=1.0',      'User-Agent': 'axios/1.7.7',      'Content-Length': '286',      'Accept-Encoding': 'gzip, compress, deflate, br'    },    method: 'put',    url: 'https://openam-computershare-use1-dev.id.forgerock.io/am/json/realms/root/realms/alpha/realm-config/services/amSessionPropertyWhitelist',    data: '{"_id":"","_type":{"_id":"amSessionPropertyWhitelist","collection":false,"name":"Session Property Whitelist Service"},"sessionPropertyWhitelist":["AMCtxId"],"whitelistedQueryProperties":[]}'  },  code: 'ERR_BAD_REQUEST',  status: 404} `

**Comment by christian-brindley** [comment]
What version of fr-config-push is this? Is it a duplicate of https://github.com/ForgeRock/fr-config-manager/issues/207?

**Comment by kevswiss** [comment]
This happened with an older version of fr-config-push. Cannot reproduce with latest version
