### ISSUE TITLE
Renaming nodes can lead to corrupted journey

### ISSUE THREAD

**Issue by kevswiss** [ForgeRock/fr-config-manager#224]
Node has been renamed in sandbox, then pulled and pushed to dev. This caused 2 nodes to be in the repo with the same ID but different name. Since the renamed node also had changed outcomes it caused the journey to be corrupted.

POA
- Reproduce the issue
- See if it helps when we manually delete the specific journey directory before the pull
- If that fixes it, have a new option --clean which initially only applies to journeys. For each journey, this simply removes its directory before processing

**Comment by christian-brindley** [comment]
Reproduced issue as follows

- Create a journey with a scripted decision node named "sdn1" and two outcomes - `outcome1` `outcome2`
- fr-config-pull the journey
- Update the scripted decision node to "sdn2", and add a third outcome, ending up with `outcome1` `outcome2` `outcome3`
- fr-config-pull the journey
- fr-config-push the journey

The journey will show the node with the new name "sdn2" but the old outcomes `outcome1` `outcome2`. `outcome3` is missing.

Trying with the new branch and the `--clean` option fixes this behaviour.

**Comment by christian-brindley** [comment]
There seems to be a timing issue when pulling with dependencies - maybe an inner journey issue? E.g.

```
% fr-config-pull journeys --clean --pull-dependencies 
Getting journeys
ERROR - can't save tenant-config/realms/bravo/journeys/Login/nodes/Page Node - a12bc72f-ad97-4f1e-a789-a1fa3dd566c8/Platform Username - 7354982f-57b6-4b04-9ddc-f1dd1e1e07d0.json
```
