### ISSUE TITLE
CLI command `fr-config-push` with option `secrets` throws `OPTION is not defined` error

### ISSUE THREAD

**Issue by jorgesanchezperez** [ForgeRock/fr-config-manager#31]
The CLI command `fr-config-push secrets` throws the error `ReferenceError: OPTION is not defined`

Reviewing the source I have find that the file `update-secrets.js` doesn't import the constant `OPTION` defined in the `cli-options.js` used in the update-secrets, so that throws the `ReferenceError` exception in runtime.

Could be this is not the only case, I suggest to review all places where the constant `OPTION` is used to fix the import if necessary.

**Comment by dragos-panaitescu-fr** [comment]
Created PR for the issue: https://github.com/ForgeRock/fr-config-manager/pull/32
