### ISSUE TITLE
404 on updating services fix

### ISSUE THREAD

**Issue by ryanzwe** [ForgeRock/fr-config-manager#97]
Hi All, 

While using the fr-config-push secrets command we are experiencing a 404 when performing this on a new resource, updating 
`  await restPut(
                descendentRequestUrl,
                descendentFile,
                token,
                "protocol=1.0,resource=1.0"
              );`

to
`  await restPut(
                descendentRequestUrl,
                descendentFile,
                token,
                "protocol=2.0,resource=1.0"
              );`
resolved this issue in the `update-services.js` file

**Comment by christian-brindley** [comment]
Resolved
